{{- if .Values.detector.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: poding-detector
  namespace: {{ include "poding.namespace" . }}
  labels:
    {{- include "poding.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "poding.fullname" . }}-detector
  labels:
    {{- include "poding.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "poding.fullname" . }}-detector
  labels:
    {{- include "poding.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "poding.fullname" . }}-detector
subjects:
  - kind: ServiceAccount
    name: poding-detector
    namespace: {{ include "poding.namespace" . }}
{{- end }}
