apiVersion: v1
kind: Service
metadata:
  name: poding-metrics-exporter
  namespace: poding-system
spec:
  selector:
    app: poding-metrics-exporter
  ports:
    - name: metrics
      port: 9108
      targetPort: metrics
