apiVersion: v1
kind: ConfigMap
metadata:
  name: poding-config
  namespace: poding-system
data:
  config.yaml: |
    falco:
      namespace: poding-system
      target: app.kubernetes.io/name=falco
      command_template: kubectl logs -f -n {namespace} -l {target} -c falco --tail=20 --since=30s --prefix --max-log-requests=10

    hubble:
      server: hubble-relay.kube-system.svc.cluster.local:80
      command_template: hubble observe --server {server} --follow --since 30s
      relay_namespace: kube-system
      relay_service: svc/hubble-relay
      relay_local_port: "4245"
      relay_remote_port: "80"
      port_forward_command: cilium hubble port-forward
      fallback_port_forward_command: kubectl port-forward -n {relay_namespace} {relay_service} {relay_local_port}:{relay_remote_port}

    pipeline:
      cluster_name: poding-lab
      results_dir: ./results
      run_label: ""
      keep_latest: "true"
      logs_dir: logs
      startup_sleep: "3"
      api_host: 0.0.0.0
      api_port: "8080"
